openapi: 3.0.2
servers:
  - url: https://localhost

info:
  description: This service provides about semantic artefacts.
  title: MOD API
  version: 0.0.1

tags:
  - name: Artefact
    description: Get information about a semantic artefact.
  - name: Catalogue
    description: Get information about the semantic artefact catalogue.
  - name: Search
    description: Search for semantic artefacts.
  - name: Documentation
    description: Get documentation about the service.

components:

  parameters:
    format_param:
      description: | 
        The response format.
        
        This will override any value of `Accept` in the request headers.
        Possible values are `html`, `json`, `ttl` and `xml`. The default value is `html`.
      name: format
      in: query
      schema:
        type: string
        enum: 
          - html
          - json
          - ttl
          - xml
        default: html
        example: html

    artefact:
      description: The UID of the artefact.
      name: artefact
      in: path
      required: true
      schema:
        type: string

  responses:

    notes:
      description: "OK"
      content:
        text/html:
          schema:
            $ref: "#/components/schemas/html"

    artefact:
      description: "OK"
      content:
        text/html:
          schema:
            $ref: "#/components/schemas/html"
        text/turtle:
          schema:
            type: string
        application/json:
          schema:
           $ref: "#/components/schemas/SemanticArtefact"
        application/rdf+xml:
          schema:
            type: string

    catalog:
      description: "OK"
      content:
        text/html:
          schema:
            $ref: "#/components/schemas/html"
        text/turtle:
          schema:
            type: string
        application/json:
          schema:
           $ref: "#/components/schemas/SemanticArtfeactCatalog"
        application/rdf+xml:
          schema:
            type: string

    distribution:
      description: "OK"
      content:
        text/html:
          schema:
            $ref: "#/components/schemas/html"
        text/turtle:
          schema:
            type: string
        application/json:
          schema:
           $ref: "#/components/schemas/SemanticArtefactDistribution"
        application/rdf+xml:
          schema:
            type: string

    record:
      description: "OK"
      content:
        text/html:
          schema:
            $ref: "#/components/schemas/html"
        text/turtle:
          schema:
            type: string
        application/json:
          schema:
           $ref: "#/components/schemas/SemanticArtefactCatalogRecord"
        application/rdf+xml:
          schema:
            type: string

    error_message:
      description: The provided parameters are incorrect.
      content:
        text/html:
          schema:
            $ref: "#/components/schemas/error_message"

  schemas:
    error_message:
      title: error message
      description: A text message describing an error.
      type: string
      maxLength: 256

    html:
      description: A html page.
      type: string

    SemanticArtefact:
      title: Semantic Artefact
      description: Resource published or curated by a single agent.
      type: object

    SemanticArtfeactCatalog:
      title: Semantic Artfeact Catalog
      description: A curated collection of metadata about resources (e.g., datasets and data services in the context of a data catalog).
      type: object
      properties:
        catalog:
          title: catalog
          description: A catalog whose contents are of interest in the context of this catalog.
          $ref: "#/components/schemas/SemanticArtfeactCatalog"
        dataset:
          title: dataset
          description: A collection of data that is listed in the catalog.
          $ref: "#/components/schemas/Dataset"
        record:
          title: record
          description: A record describing the registration of a single dataset or data service that is part of the catalog.
          type: array
          items:
            $ref: "#/components/schemas/SemanticArtefactCatalogRecord"
        service:
          title: service
          description: A site or endpoint that is listed in the catalog.
          $ref: "#/components/schemas/SemanticArtefactService"
        themeTaxonomy:
          title: theme taxonomy
          description: The knowledge organization system (KOS) used to classify catalog's datasets.
          $ref: "#/components/schemas/SemanticArtefact"

    Dataset:
      title: Dataset
      description: A collection of data, published or curated by a single source, and available for access or download in one or more represenations.
      type: object
      properties:
        distribution:
          title: distribution
          description: An available distribution of the dataset.
          $ref: "#/components/schemas/SemanticArtefactDistribution"
  
    SemanticArtefactDistribution:
      title: Semantic Artefact Distribution
      description: A specific representation of a dataset. A dataset might be available in multiple serializations that may differ in various ways, including natural language, media-type or format, schematic organization, temporal and spatial resolution, level of detail or profiles (which might specify any or all of the above).
      type: object
      properties:
        accessURL:
          title: access address
          description: A URL of a resource that gives access to a distribution of the dataset. E.g. landing page, feed, SPARQL endpoint. Use for all cases except a simple download link, in which case downloadURL is preferred.
          $ref: "#/components/schemas/Resource"
        byteSize:
          title: byte size
          description: The size of a distribution in bytes.
          type: number
        compressFormat:
          title: compression format
          description: The compression format of the distribution in which the data is contained in a compressed form, e.g. to reduce the size of the downloadable file.
          type: string
        downloadURL:
          title: download URL
          description: The URL of the downloadable file in a given format. E.g. CSV file or RDF file. The format is indicated by the distribution's dct:format and/or dcat:mediaType.
          $ref: "#/components/schemas/Resource"
        hasRepresentationLanguage:
          title: representation language
          description: A language that is used to create an ontology.
          type: string
          format: uri
        hasSyntax:
          title: syntax
          description: The syntax followed in the creation of an ontology.
          type: string
          format: uri
        mediaType:
          title: media type
          description: The media type of the distribution as defined by IANA.
          type: "#/components/schemas/MediaType"
        packageFormat:
          title: packaging format
          description: The package format of the distribution in which one or more data files are grouped together, e.g. to enable a set of related files to be downloaded together.
          type: "#/components/schemas/MediaType"
        prefLabelProperty:
          title: object preferred label property
          description: Property used to specify objects' preferred label.
          type: string
          format: uri
        synonymProperty:
          title: object synonym property
          description: Property used to specify objects' synonyms.
          type: string
          format: uri
        definitionProperty:
          title: object definition property
          description: Property used to specify objects' definition.
          type: string
          format: uri
        authorProperty:
          title: object author property
          description: Property used to specify objects's author.
          type: string
          format: uri
        obsoleteProperty:
          title: object obsolete property
          description: Property used to specify obsolete objects.
          type: string
          format: uri
        hierarchyProperty:
          title: transitive hierarchy property
          description: Property used to specify the hierarchy (e.g. rdfs:subClassOf or skos:broader).
          type: string
          format: uri
        obsoleteParent:
          title: transitive hierarchy property
          description: Property used to specify the root of an obsolete branch in the ontology.  
          type: string
          format: uri
        sampleQueries:
          title: sample queries
          description: A set of queries (may be SPARQL, DL Queries) that are provided along with an ontology.
          type: string
          format: uri
        metrics:
          title: metrics
          description: A generic property to store any metrics related to the ontology.
          type: object

    SemanticArtefactCatalogRecord:
      # sub class dcat:Resource
      title: Semantic Artefact Catalog Record
      description: A record in a data catalog, describing the registration of a single dataset or data service.
      type: object

    SemanticArtefactService:
      # sub class of dcat:Resource
      title: Semantic Artefact Service
      description: A site or end-point providing operations related to the discovery of, access to, or processing functions on, data or related resources.
      type: object
      properties:
        endpointDescription:
          title: description of service end-point
          description: A description of the service end-point, including its operations, parameters etc.
          type: object
        endpointURL:
          title: service end-point
          description: The root location or primary endpoint of the service (a web-resolvable IRI).
          $ref: "#/components/schemas/Resource"
        servesDataset:
          tile: serves dataset
          description: A collection of data that this DataService can distribute.
          $ref: "#/components/schemas/Dataset"

    Resource:
      title: Resource
      description: A rdfs Resource
      type: object

    MediaType:
      title: MediaType
      description: A dct MediaType
      type: object

paths:
  # Infomation about the semantic artefact catalogue
  /catalogue:
    parameters:
      - $ref: "#/components/parameters/format_param"

    get:
      tags:
        - Catalogue
      summary: Get information about the semantic artefact catalogue
      operationId: catalogue
      responses:
        "200":
          $ref: "#/components/responses/catalog"

  # API Documentation
  /doc/api:
    get:
      tags:
        - Documentation
      summary: Get the API documentation
      operationId: docs
      responses:
        "200":
          $ref: "#/components/responses/notes"

  # Information about a semantic artefacts
  /artefact/{artefact}:
    parameters:
      - $ref: "#/components/parameters/artefact"
      - $ref: "#/components/parameters/format_param"

    get:
      tags:
        - Artefact
      summary: Get information about a semantic artefact.
      description: Retrieves information about a semantic artefact.
      operationId: artefact
      responses:
        "200":
          $ref: "#/components/responses/artefact"
        "404":
          $ref: "#/components/responses/error_message"

  # Information about a semantic artefact distribution
  /artefact/{artefact}/distribution:
    parameters:
      - $ref: "#/components/parameters/artefact"
      - $ref: "#/components/parameters/format_param"

    get:
      tags:
        - Artefact
      summary: Get information about a semantic artefact distribution.
      description: Retrieves information about a semantic artefact distribution.
      operationId: getDistribution
      responses:
        "200":
          $ref: "#/components/responses/distribution"
        "404":
          $ref: "#/components/responses/error_message"


  # Information about a semantic artefact catalog record
  /artefact/{artefact}/record:
    parameters:
      - $ref: "#/components/parameters/artefact"
      - $ref: "#/components/parameters/format_param"

    get:
      tags:
        - Artefact
      summary: Get information about a semantic artefact catalog record.
      description: Retrieves information about a semantic artefact catalog record.
      operationId: getRecord
      responses:
        "200":
          $ref: "#/components/responses/record"
        "404":
          $ref: "#/components/responses/error_message"


